### ISSUE TITLE
Remove any instances of "fragile" class-checking 

### ISSUE THREAD

**Issue by ppanko** [PcAux-Package/PcAux#32]
Several pieces of code have something along the lines of: 

```r
class(variable) == "numeric"
```

This is very fragile (if `variable` belongs to multiple classes, the check may fail if the length of `class(variable)` is expected to be 1), so we don't want to rely on it. Instead, these types of statements should be changed to: 

```r
is.numeric(variable)
```

For classes that do not have an appropriate `is.` method, we want to use the `inherits` function: 

```r
inherits(variable, "PcAuxData")
```

**Comment by ppanko** [comment]
Here are all of the instances I have found: 

https://github.com/PcAux-Package/PcAux/blob/3d4a67f91fca497f03f6063134653ce3d21420ed/source/PcAux/R/helperFunctions.R#L59-L66

https://github.com/PcAux-Package/PcAux/blob/3d4a67f91fca497f03f6063134653ce3d21420ed/source/PcAux/R/exportedHelperFunctions.R#L153-L159

https://github.com/PcAux-Package/PcAux/blob/3d4a67f91fca497f03f6063134653ce3d21420ed/source/PcAux/R/miWithPcAux.R#L66-L70

https://github.com/PcAux-Package/PcAux/blob/3d4a67f91fca497f03f6063134653ce3d21420ed/source/PcAux/R/miWithPcAux.R#L189-L192

https://github.com/PcAux-Package/PcAux/blob/9fdd9a6d99ef7259efc9755dd70ea6d4b0a4eca3/source/PcAux/R/subroutines.R#L391-L398

**Comment by kylelang** [comment]
This project is no longer actively developed here, so I'm archiving this repository. In preparation thereof, I'm closing all open issues.
