### ISSUE TITLE
Use "testthat" to run unit tests 

### ISSUE THREAD

**Issue by ppanko** [PcAux-Package/PcAux#33]
The `testthat` package is convenient for writing self-documenting unit tests that can be run during the package checking process (using either `R CMD check` or `devtools::check()`). I suggest we adjust our unit tests to incorporate `testthat`.

**Comment by kylelang** [comment]
In principle, I certainly agree. I would very much prefer to use testthat and run proper unit tests. Unfortunately, the tests we currently have are not true unit tests (they simultaneously test many computational units). Also, the majority of our tests are interactive and cannot be run in a "batch" style. So, moving to using testthat would require developing an entirely new set of tests. The move is still a good idea, but it will be a lot of work.

**Comment by ppanko** [comment]
I agree, I don't think PcAux -in its current form- can move entirely to a batch testing model.

**Comment by kylelang** [comment]
This project is no longer actively developed here, so I'm archiving this repository. In preparation thereof, I'm closing all open issues.
