### ISSUE TITLE
Make parallelMice consistent with the mice call in serial 

### ISSUE THREAD

**Issue by ppanko** [PcAux-Package/PcAux#35]
There is some inconsistency in parallelMice: namely, it does not create a `miceObject` inside the `PcAuxData` class.

**Comment by kylelang** [comment]
We need to be careful with this one. We don't create a `miceObject` when running parallelMice because that function doesn't produce a single `mids` object. The `miceObject` slot is supposed to be a `mids` object upon which we can call any method that works with `mids`.

**Comment by ppanko** [comment]
Right; I don't have a good reasoning for implementing this besides maintaining consistency. After all, It's not that hard to make your own `mids` object, if necessary.

**Comment by kylelang** [comment]
This project is no longer actively developed here, so I'm archiving this repository. In preparation thereof, I'm closing all open issues.
